version: "3.8"

services:
  web:
    build: ./web/
    restart: always
    environment:
      - DB_HOST="mysql"
      - DB_USER="root"
      - DB_PASSWORD="root"
      - DB_DATABASE="cloud"
    ports:
      - 8080:8080
    depends_on:
      - mysql
    volumes:
      - app_data:/app/data

  mysql:
    build: ./data/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - mysql-data:/var/lib/MySQL

volumes:
  mysql-data:
  app_data:
